title: Gee Of All Trades
author: Jogee Nonato
email: jogeenonato@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This site will take you to the journey of a career pivoter and philomat who wants to start her career in tech.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jogeenonato # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
